# -*- coding: utf-8 -*-
"""seleccion

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bgc2a6FFFhbuC_zBTYqOUuJdw0KSpW8F
"""

A = []
B = []
C = []
D = []

#Parte1

listatres = ['verde', 'verde', 'amarillo', 'rojo', 'verde', 'amarillo', 'rojo', 'amarillo', 'rojo', 'verde']

for i in range(len(listatres)):
    if listatres[i] not in C:
      C.append(listatres[i])
print(C)  


#parte2

etiquetas = ['verde', 'verde', 'amarillo', 'rojo', 'verde', 'amarillo', 'rojo', 'amarillo', 'rojo', 'verde']
elementos = [0, 2, 4, 8]
etiqueta = ['rojo']

#print(etiquetas[2])

for it in elementos:
  if etiqueta[0] == etiquetas[it]:
     D.append(it)

print(D)


listauno = [3,5,7,10,15,16]
listados = [4,10,5,8]
#Parte3

for it in listauno:
  if it not in listados:
    B.append(it)

# 4 parte
for it in listauno:
  if it in listados:
    A.append(it)

print(B)
print(len(A))

def etiquetas(listatres1):
  listatres = ['verde', 'verde', 'amarillo', 'rojo', 'verde', 'amarillo', 'rojo', 'amarillo', 'rojo', 'verde']
  C = []
  for i in range(len(listatres)):
    if listatres[i] not in C:
      C.append(listatres[i])
  etiquetas(listatres1)
  return
  print(C)