# -*- coding: utf-8 -*-
"""reto1_jeison_castelblanco.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QBNvSTNS7OUJ6GY_-jfjdhZL7D6eF50p
"""



import math
def reto_uno(C):
  M = (2*C+4)
  CM = math.floor((C+M)/5)
  if CM <= 20:
    tipo = "uno"
  elif 21 <= CM <= 30:
    tipo = "dos"
  elif 31 <= CM <= 50:
    tipo = "tres"
  elif CM > 50:
    tipo = "cuatro"
  else:  
    tipo = "NOAPLICA"
  return (str(C) + " " + str(M) + " " + str(CM) + '\n' + tipo)
print(reto_uno(178))