# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fOeXnbXN0K5Jlh1pGGU-P0nDQzhYv-2X
"""

#Reto2
A = input()
B = input()
resultados = input()

ventaja = 0
for x in resultados:
  if(x in A):
    ventaja += 1
  if(x in B):
    ventaja -= 1
  if(ventaja > 0):
    print("P",end="")
  elif(ventaja < 0):
    print("N",end="")
  else:
    print("I",end="")